### ISSUE TITLE
Accept ssh host keys automatically

### ISSUE THREAD

**Issue by Sanchiz** [propeoplemd/cibox#385]
We should accept host keys automatically:

```yaml
- name: Accept ssh host keys automatically for root
      lineinfile:
        dest: .ssh/config
        line: 'Host *\nStrictHostKeyChecking no'
        create: yes
      sudo: yes
      sudo_user: root

    - name: Accept ssh host keys automatically for jenkins
      lineinfile:
        dest: .ssh/config
        line: 'Host *\nStrictHostKeyChecking no'
        create: yes
      sudo: yes
      sudo_user: jenkins
```
