### ISSUE TITLE
Speedup loops

### ISSUE THREAD

**Issue by podarok** [propeoplemd/cibox#397]
```yml
---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    modules_list:
      - { name: test1, status: true }
      - { name: test2, status: false }
      - { name: test3, status: true }
  tasks:
    - debug: msg="{{ modules_list|selectattr('status', 'equalto', true)|map(attribute='name')|join(' ') }}"
    
    
```
