### ISSUE TITLE
Injecting reinstalls back to CIBOX

### ISSUE THREAD

**Issue by podarok** [propeoplemd/cibox#83]
We should inject our work to CIBOX

This issue will be used for collecting thoughts about current implementation

DIfferent solr reindexing commands
searchapi
```sh
sudo drush -y search-api-clear -l http://stage.steptoe-johnson.com || true
sudo drush -y search-api-index -l http://stage.steptoe-johnson.com || true
```

apachesolr
```sh
sudo drush -y solr-mark-all -l http://istage.steptoe-johnson.com || true
sudo drush -y solr-index -l http://istage.steptoe-johnson.com || true
```
Let's have an option var for selecting proper one. Or a tag, that sounds better, because we will have ability to run only selected tags

**Comment by Sanchiz** [comment]
Features should be injected from:

https://github.com/propeoplemd/TFALL/blob/master/docroot/reinstall.yml
https://github.com/propeoplemd/NAS/blob/master/docroot/reinstall.yml
https://github.com/propeoplemd/asc/blob/master/docroot/reinstall.yml

**Comment by Sanchiz** [comment]
PR: https://github.com/propeoplemd/cibox/pull/205

**Comment by Sanchiz** [comment]
For review before processing:
https://github.com/propeoplemd/code/blob/master/docroot/reinstall.yml
https://github.com/propeoplemd/ANC/blob/master/drupal/reinstall.yml
https://github.com/propeoplemd/asc/blob/master/docroot/reinstall.yml
https://github.com/propeoplemd/NAS/blob/master/docroot/reinstall.yml
https://github.com/propeoplemd/TFALL/blob/master/docroot/reinstall.yml

**Comment by podarok** [comment]
Import D8 back from https://github.com/InternetDevels/d8drupalua

**Comment by podarok** [comment]
Roadmap for this task
- rename pre && post . ymls
- remove include from folder names
- split environment configs to files
- boolean TRUE FALSE for optional commands
```yml
---
- name: Loop with when conditionals
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    list:
      - name: peter
        state: true
      - name: silie
        state: false
  tasks:
    - name: Debug when state equals true
      with_items: list
      when: item.state
      debug:
        msg={{ item.name }}

```
- add pre_settings and post_settings config loops for settings.php
- Move registry rebuild to SQL profile
